### ISSUE TITLE
Due to babel changes, boilerplate does not work any longer

### ISSUE THREAD

**Issue by wpernath** [melonjs/es6-boilerplate#2]
If you're trying to run `npm run dev` with this boilerplate project, you get the following exception:

ERROR in ./node_modules/melonjs/dist/melonjs.module.js 3:9
Module parse failed: Identifier '_set2' has already been declared (3:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| function _set2(target, property, value, receiver) { if (typeof Reflect !== "undefined" && Reflect.set) { _set2 = Reflect.set; } else { _set2 = function set(target, property, value, receiver) { var base = _superPropBase(target, property); var desc; if (base) { desc = Object.getOwnPropertyDescriptor(base, property); if (desc.set) { desc.set.call(receiver, value); return true; } else if (!desc.writable) { return false; } } desc = Object.getOwnPropertyDescriptor(receiver, property); if (desc) { if (!desc.writable) { return false; } desc.value = value; Object.defineProperty(receiver, property, desc); } else { _defineProperty(receiver, property, value); } return true; }; } return _set2(target, property, value, receiver); }
|
> function _set2(target, property, value, receiver, isStrict) { var s = _set2(target, property, value, receiver || target); if (!s && isStrict) { throw new Error('failed to set property'); } return value; }
|
| function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }
 @ ./src/index.js 3:0-106 9:0-14 11:7-17 23:6-29 23:30-45 28:2-12 30:2-20 32:2-16 34:4-13 34:14-24 35:4-13 35:14-24 37:4-17 39:4-16 39:17-27

webpack 5.74.0 compiled with 1 error in 9124 ms

The fix for this is to change babel version, fix webpack.config.js etc. I am going to provide a pull request in a few minutes.

**Comment by obiot** [comment]
thanks again ! (see my reply in the PR)
